//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Foto()
        {
            this.Incidencias = new HashSet<Incidencia>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Foto1 { get; set; }
        public string Thumbnail1 { get; set; }
        public string Ruta1 { get; set; }
        public Nullable<int> Foto2 { get; set; }
        public string Thumbnail2 { get; set; }
        public string Ruta2 { get; set; }
        public Nullable<int> Foto3 { get; set; }
        public string Thumbnail3 { get; set; }
        public string Ruta3 { get; set; }
        public Nullable<int> Foto4 { get; set; }
        public string Thumbnail4 { get; set; }
        public string Ruta4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidencia> Incidencias { get; set; }
    }
}
