//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVPWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioSVPWebIncidencia
    {
        public int Id { get; set; }
        public Nullable<int> NLegSVPWeb { get; set; }
        public Nullable<int> IdIncidencia { get; set; }
        public string ObsSVPWeb { get; set; }
        public string idSAP { get; set; }
    
        public virtual Incidencia Incidencia { get; set; }
    }
}
