//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVPWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incidencia()
        {
            this.UsuarioSVPWebIncidencias = new HashSet<UsuarioSVPWebIncidencia>();
        }
    
        public int Id { get; set; }
        public string Estado { get; set; }
        public int NlegajoUMobile { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Zona { get; set; }
        public int IdPhotoSet { get; set; }
        public string ObsMobile { get; set; }
        public string Calle { get; set; }
        public string Altura { get; set; }
        public string Localidad { get; set; }
        public Nullable<decimal> GPSLat { get; set; }
        public Nullable<decimal> GPSLon { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
    
        public virtual Foto Foto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioSVPWebIncidencia> UsuarioSVPWebIncidencias { get; set; }
    }
}
